### PR TITLE
Respect auto commit settings while consuming batches

### PR DESCRIPTION
**Pull request by vuza**
The following code reads all messages on topic `role` and commits them, despite the disabled auto commit option.

```javascript
const consumer = new NConsumer(null, {
  logger: {
    debug: msg => console.log(msg),
    info: msg => console.log(msg),
    warn: msg => console.log(msg),
    error: msg => console.log(msg)
  },
  noptions: {
    'metadata.broker.list': config.get('kafka.connectionString'),
    'group.id': `${config.get('kafka.groupIdPrefix')}-test-consumer`,
    'enable.auto.commit': false
  },
  tconf: {
    'auto.offset.reset': 'earliest'
  }
})

consumer.connect(false)
  .then(() => consumer.addSubscriptions(['role']))
  .then(() => {
    consumer.consume((message, cb) => {
      console.log(message)
      cb()
    })
  })
```
This PR fixes this, committing only if auto commit is enabled! With this PR, the code above does not commit any messages, as expected!

### CODE REVIEW

**Comment by krystianity** [comment]
Committing in "1:n" mode is actually aimed for, even if "enable.auto.commit" is disabled.
As batch mode is actually build for exactly once delivery and seen as a different mode, compared to: manual commit and auto commit.

When using (or not using) auto.commit we currently expect to use the non batch mode via:
```
consumer.consume(); //<- no cb here
consumer.on("message" => {});
```

I am not 100% sure yet if its a good idea to move manual committing into batch mode.
Alternatively we could throw an error if batch mode is used with "enable.auto.commit": false

**Comment by vuza** [comment]
Alright, I'm gonna give the none batch mode a try and see if it fullfills
our requirements. In any case an exception, a warning or at least a comment
in the method's description to show the developer's intent would be nice to
my opinion. :)

**Comment by vuza** [comment]
Using `consume.on('message', () => ...)` works for me, thank you! Comment, exception or logged warning would be nice to my opinion.

Thank you for clarification!!

**Comment by krystianity** [comment]
Added this [PR](https://github.com/nodefluent/node-sinek/pull/41) to log a warning message.

**Comment by easimon** [comment]
I'd like to re-open the discussion on this topic. I am a co-worker of vuza, working on the same topic.

The proposed solution seemed to work at first, but we tested it with small amounts of messages only.

When having a topic with several millions of messages, this mode results in a completely overwhelmed node-js application, dying with "Out of memory". Sinek emitted new message events faster than we processed them.

So, using the non-batch-mode seems unsuitable for us in many ways:
First of all, we need a strict processing order per TopicPartition (TP). Our experiment seemed to push several messages for the same TP without waiting for the old ones being processed. Way more than we have partitions. I can imagine (not prove) that several messages of the same TP can overtake each other during processing this way.
Second, without any means of backpressure, our application just dies quickly in non-batch-mode due to the described observations.

Closing the loop to the batch-mode: even if not designed for manual commit in the first place -- why not support manual commit? We need this manual commit, because processing of a message can fail due to failures in another external system. In such a case, we need a possibility to shut down / pause our processor and later resume exactly at (or before -- but not after) the last message that failed. With autocommit, this is not possible.

I don't really see a reason for forbidding manual commit, and the original PR seems to have a simple solution. Am I missing something? Or is there a possibility to change your opinion to accept this PR on second thought?

**Comment by krystianity** [comment]
@easimon I will have a short discussion with my colleagues on next Monday regarding this to check if it breaks any of their stuff. I see your pain-point - if it doesn't cause any trouble for us, I will create a new PR that enables manual commits in batch mode.

**Comment by krystianity** [comment]
@easimon @vuza please checkout sinek@6.14.0, there is now an additional option called `noBatchCommits` that you can pass to `nconsumer.consume(.., {noBatchCommits: true})`, it will disable any commits during batch mode and should fulfill your wishes, without breaking any existing behaviour.

**Pull request closed without merging**
