### PR TITLE
Convert to ts

### PR DESCRIPTION
**Pull request by elmarx**
Essential migration to typescript.

This should be no functional difference to the JS sources, as the typescript-conversion only touched imports and fields/properties for classes.

All other compilation-errors have been silenced via `@ts-ignore`. They might indicate real bugs or just imprecise types, but can be addressed one-after-another. There's no need to fix all of them at once and thus a greater chance of bugs/unwanted changes.

Future development can fully leverage typescript + type-definition are already generated.

Please let me know what you think about this PR.

### CODE REVIEW

**Comment by krystianity** [comment]
U cray bro :D?

**Comment by elmarx** [comment]
I only understand trainstation.

**Comment by krystianity** [comment]
we can merge this, if you adapt to the newest version (i am freezing the code until then).
Please make sure that the new test version still runs in your branch.

**Comment by rob3000** [comment]
Closing as upgrade was completed in https://github.com/nodefluent/node-sinek/pull/154

**Pull request closed without merging**
